# Generated by Django 5.2 on 2025-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
