# Generated by Django 5.2 on 2025-04-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0005_customuser_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='socialMedia.post'),
        ),
    ]
