# Generated by Django 5.2 on 2025-04-09 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0006_customuser_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
