# Generated by Django 5.2 on 2025-04-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0011_remove_post_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
