# Generated by Django 5.2 on 2025-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0013_alter_comment_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='../static/placehoder/placeholder.jpg', null=True, upload_to='upload/User'),
        ),
    ]
