# Generated by Django 5.2 on 2025-04-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0015_alter_customuser_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/upload/User/placeholder.jpg', null=True, upload_to='upload/User'),
        ),
    ]
